# Generated by Django 5.2.13 on 2026-04-21 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tariflar_oddiy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.CharField(default='206$', help_text='Masalan: 206$ yoki 2.5mln', max_length=255)),
                ('description', models.TextField()),
                ('icon', models.CharField(max_length=255)),
                ('button_text', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Tariflar_oddiy',
                'verbose_name_plural': 'Tariflar_oddiy',
            },
        ),
        migrations.DeleteModel(
            name='Card',
        ),
        migrations.DeleteModel(
            name='Tariflar_poor',
        ),
        migrations.AlterModelOptions(
            name='about_us',
            options={'verbose_name': 'About Us', 'verbose_name_plural': 'Biz haqimizda'},
        ),
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': 'Banner', 'verbose_name_plural': 'Bannerlar'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Contact', 'verbose_name_plural': 'Aloqa'},
        ),
        migrations.AlterModelOptions(
            name='faoliyatlar',
            options={'verbose_name': 'Faoliyatlar', 'verbose_name_plural': 'Faoliyatlar'},
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name': 'FAQ', 'verbose_name_plural': 'FAQ'},
        ),
        migrations.AlterModelOptions(
            name='fikrlar',
            options={'verbose_name': 'Fikrlar', 'verbose_name_plural': 'Fikrlar'},
        ),
        migrations.AlterModelOptions(
            name='galereya',
            options={'verbose_name': 'Galereya', 'verbose_name_plural': 'Galereya'},
        ),
        migrations.AlterModelOptions(
            name='kurslar',
            options={'verbose_name': 'Kurslar', 'verbose_name_plural': 'Kurslar'},
        ),
        migrations.AlterModelOptions(
            name='number_main',
            options={'verbose_name': 'Number', 'verbose_name_plural': 'Raqamlar'},
        ),
        migrations.AlterModelOptions(
            name='number_sub',
            options={'verbose_name': 'Number_main', 'verbose_name_plural': 'Raqamlar_main'},
        ),
        migrations.AlterModelOptions(
            name='power',
            options={'verbose_name': 'Power', 'verbose_name_plural': 'Afzalliklarimiz'},
        ),
        migrations.AlterModelOptions(
            name='qabul',
            options={'verbose_name': 'Qabul', 'verbose_name_plural': 'Qabul'},
        ),
        migrations.AlterModelOptions(
            name='tariflar_pro',
            options={'verbose_name': 'Tariflar_pro', 'verbose_name_plural': 'Tariflar_pro'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Team', 'verbose_name_plural': 'Ustozlar'},
        ),
        migrations.AlterModelOptions(
            name='yangiliklar',
            options={'verbose_name': 'Yangiliklar', 'verbose_name_plural': 'Yangiliklar'},
        ),
        migrations.RenameField(
            model_name='team',
            old_name='subtitle',
            new_name='position',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='name',
        ),
        migrations.RemoveField(
            model_name='tariflar_pro',
            name='number',
        ),
        migrations.AddField(
            model_name='about_us',
            name='card2_description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="2-karta ma'lumoti"),
        ),
        migrations.AddField(
            model_name='about_us',
            name='card2_icon',
            field=models.CharField(blank=True, default='fa-chalkboard-teacher', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='about_us',
            name='card2_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='2-karta sarlavhasi'),
        ),
        migrations.AddField(
            model_name='about_us',
            name='card3_description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="3-karta ma'lumoti"),
        ),
        migrations.AddField(
            model_name='about_us',
            name='card3_icon',
            field=models.CharField(blank=True, default='fa-lightbulb', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='about_us',
            name='card3_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='3-karta sarlavhasi'),
        ),
        migrations.AddField(
            model_name='contact',
            name='address',
            field=models.CharField(default="Farg'ona shahri, Shodiyona MFY", max_length=255),
        ),
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.CharField(default='anosvoldigort47@gmail.com', max_length=255),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(default='+998 91 791 48 81', max_length=255),
        ),
        migrations.AddField(
            model_name='galereya',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='galereya/'),
        ),
        migrations.AddField(
            model_name='kurslar',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kurslar',
            name='duration',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='kurslar',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='kurslar/'),
        ),
        migrations.AddField(
            model_name='kurslar',
            name='price',
            field=models.CharField(blank=True, help_text='Masalan: 200$ / oy yoki 500,000 UZS', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tariflar_pro',
            name='price',
            field=models.CharField(default='288$', help_text='Masalan: 288$ yoki 3mln', max_length=255),
        ),
        migrations.AddField(
            model_name='team',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='team/'),
        ),
        migrations.AddField(
            model_name='team',
            name='instagram_link',
            field=models.URLField(blank=True, help_text='Instagram profil linki', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='name',
            field=models.CharField(default='Team Member', max_length=255),
        ),
        migrations.AddField(
            model_name='team',
            name='telegram_link',
            field=models.URLField(blank=True, help_text='Telegram profil linki', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='about_us',
            name='card_description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="1-karta ma'lumoti"),
        ),
        migrations.AlterField(
            model_name='about_us',
            name='card_icon',
            field=models.CharField(blank=True, default='fa-user-graduate', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='about_us',
            name='card_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='1-karta sarlavhasi'),
        ),
        migrations.AlterField(
            model_name='about_us',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='about_us/'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='banners/'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='description',
            field=models.TextField(default="Forma orqali murojaat qoldiring. Administrator siz bilan bog'lanib, kurs, jadval va qabul jarayoni bo'yicha batafsil ma'lumot beradi."),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subtitle',
            field=models.CharField(blank=True, default="Bog'lanish", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='title',
            field=models.CharField(default='Savolingizga tez javob beramiz', max_length=255),
        ),
        migrations.AlterField(
            model_name='faq',
            name='text',
            field=models.TextField(help_text='Javob matnini bu yerga kiriting'),
        ),
        migrations.AlterField(
            model_name='fikrlar',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='fikrlar/'),
        ),
        migrations.AlterField(
            model_name='number_main',
            name='number',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='number_sub',
            name='number',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='number_sub',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='yangiliklar',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='yangiliklar/'),
        ),
    ]
