# Generated by Django 5.2.13 on 2026-04-15 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about_us',
            options={'verbose_name': 'About Us', 'verbose_name_plural': 'Biz haqimizda'},
        ),
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': 'Banner', 'verbose_name_plural': 'Bannerlar'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Contact', 'verbose_name_plural': 'Aloqa'},
        ),
        migrations.AlterModelOptions(
            name='faoliyatlar',
            options={'verbose_name': 'Faoliyatlar', 'verbose_name_plural': 'Faoliyatlar'},
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name': 'FAQ', 'verbose_name_plural': 'FAQ'},
        ),
        migrations.AlterModelOptions(
            name='fikrlar',
            options={'verbose_name': 'Fikrlar', 'verbose_name_plural': 'Fikrlar'},
        ),
        migrations.AlterModelOptions(
            name='galereya',
            options={'verbose_name': 'Galereya', 'verbose_name_plural': 'Galereya'},
        ),
        migrations.AlterModelOptions(
            name='kurslar',
            options={'verbose_name': 'Kurslar', 'verbose_name_plural': 'Kurslar'},
        ),
        migrations.AlterModelOptions(
            name='number_main',
            options={'verbose_name': 'Number', 'verbose_name_plural': 'Raqamlar'},
        ),
        migrations.AlterModelOptions(
            name='number_sub',
            options={'verbose_name': 'Number', 'verbose_name_plural': 'Raqamlar'},
        ),
        migrations.AlterModelOptions(
            name='power',
            options={'verbose_name': 'Power', 'verbose_name_plural': 'Afzalliklarimiz'},
        ),
        migrations.AlterModelOptions(
            name='qabul',
            options={'verbose_name': 'Qabul', 'verbose_name_plural': 'Qabul'},
        ),
        migrations.AlterModelOptions(
            name='tariflar_poor',
            options={'verbose_name': 'Tariflar_poor', 'verbose_name_plural': 'Tariflar_poor'},
        ),
        migrations.AlterModelOptions(
            name='tariflar_pro',
            options={'verbose_name': 'Tariflar_pro', 'verbose_name_plural': 'Tariflar_pro'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Team', 'verbose_name_plural': 'Ustozlar'},
        ),
        migrations.AlterModelOptions(
            name='yangiliklar',
            options={'verbose_name': 'Yangiliklar', 'verbose_name_plural': 'Yangiliklar'},
        ),
    ]
