# Generated by Django 5.2.13 on 2026-04-15 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_about_us_options_alter_banner_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Card',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='subtitle',
            new_name='position',
        ),
        migrations.AddField(
            model_name='galereya',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='galereya/'),
        ),
        migrations.AddField(
            model_name='kurslar',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kurslar',
            name='duration',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='kurslar',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='kurslar/'),
        ),
        migrations.AddField(
            model_name='kurslar',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='team/'),
        ),
        migrations.AddField(
            model_name='team',
            name='name',
            field=models.CharField(default='Team Member', max_length=255),
        ),
        migrations.AlterField(
            model_name='about_us',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='about_us/'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='banners/'),
        ),
        migrations.AlterField(
            model_name='fikrlar',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='fikrlar/'),
        ),
        migrations.AlterField(
            model_name='team',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='yangiliklar',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='yangiliklar/'),
        ),
    ]
